{% set version = "2.1.0" %}

package:
  name: flask-assets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Flask-Assets/Flask-Assets-{{ version }}.tar.gz
  sha256: f84d6532ffe59c9ff352885e8740ff4da25c0bcfacd805f0a806815e44354813

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - flask >=0.8
    - webassets >={{ version }}

test:
  imports:
    - flask_assets

about:
  home: http://github.com/miracle2k/flask-assets
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Asset management for Flask, to compress and merge CSS and Javascript files'
  doc_url: https://flask-assets.readthedocs.io/
  dev_url: http://github.com/miracle2k/flask-assets

extra:
  recipe-maintainers:
    - pmlandwehr
